z# SLF4J SimpleLogger configuration
# Set bitcoinj logging level to WARN only
org.slf4j.simpleLogger.log.org.bitcoinj=warn

# Set default logging level to WARN to suppress all other INFO messages
org.slf4j.simpleLogger.defaultLogLevel=warn