name: build-all

on:
  push:
    branches:
      - main
      - dev
    tags:
      - "v**"
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        if: github.event.pull_request.draft == false

      # - name: Setup GraalVM JDK 21 via SDKMAN (FOR TESTING WITH ACT)
      #   shell: bash
      #   run: |
      #     curl -s "https://get.sdkman.io" | bash
      #     source "$HOME/.sdkman/bin/sdkman-init.sh"
      #     sdk install java 21.0.2-graalce
      #     echo "JAVA_HOME=$HOME/.sdkman/candidates/java/21.0.2-graalce" >> $GITHUB_ENV
      #     echo "$HOME/.sdkman/candidates/java/21.0.2-graalce/bin" >> $GITHUB_PATH
          
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'

      - name: Verify Java installation
        run: |
          java -version
          native-image --version

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      - name: Build native image
        run: ./mvnw clean package -Pnative -DskipTests -Dnative.march=x86-64

      - name: Make daemon executable
        run: chmod +x target/xlite-daemon

      - name: Rename executable
        run: mv target/xlite-daemon target/xlite-daemon-linux64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-linux
          path: |
            target/xlite-daemon-linux64

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: XLite Daemon ${{ github.ref_name}}
          prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}
          files: |
            target/xlite-daemon-linux64

  build_mac:
    runs-on: macos-15-intel
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        if: github.event.pull_request.draft == false

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'

      - name: Verify Java installation
        run: |
          java -version
          native-image --version

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      - name: Build native image
        run: ./mvnw clean package -Pnative -DskipTests -Dnative.march=x86-64

      - name: Make daemon executable
        run: chmod +x target/xlite-daemon

      - name: Rename executable
        run: mv target/xlite-daemon target/xlite-daemon-osx64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-mac
          path: |
            target/xlite-daemon-osx64

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: XLite Daemon ${{ github.ref_name}}
          prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}
          files: |
            target/xlite-daemon-osx64

  build_win:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        if: github.event.pull_request.draft == false

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'

      - name: Verify Java installation
        run: |
          java -version
          native-image --version

      - name: Install Visual Studio Build Tools
        run: |
          choco install -y visualstudio2022buildtools --installargs "--add Microsoft.VisualStudio.Workload.VCTools --quiet --wait"

      - name: Build native image
        run: .\mvnw.cmd clean package -Pnative -DskipTests "-Dnative.march=x86-64"        

      - name: Rename executable
        run: Rename-Item target\xlite-daemon.exe xlite-daemon-win64.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-win
          path: target\xlite-daemon-win64.exe

      - name: Create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: XLite Daemon ${{ github.ref_name}}
          prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}
          files: target/xlite-daemon-win64.exe